"""auth migration

Revision ID: 374a0d5cbd39
Revises: 
Create Date: 2026-03-28 00:23:13.365690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374a0d5cbd39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permissions_code')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tenants_name')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('link_user_tenant_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fk_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='link_user_tenant_request_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fk_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_tenant_id', 'fk_user_id', 'status', name='uq_link_user_tenant_requests_tenant_user_status')
    )
    op.create_index(op.f('ix_link_user_tenant_requests_fk_tenant_id'), 'link_user_tenant_requests', ['fk_tenant_id'], unique=False)
    op.create_index(op.f('ix_link_user_tenant_requests_fk_user_id'), 'link_user_tenant_requests', ['fk_user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_role_id', sa.Uuid(), nullable=False),
    sa.Column('fk_permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fk_permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['fk_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_role_id', 'fk_permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_fk_permission_id'), 'role_permissions', ['fk_permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_fk_role_id'), 'role_permissions', ['fk_role_id'], unique=False)
    op.create_table('user_tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_user_id', sa.Uuid(), nullable=False),
    sa.Column('fk_tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fk_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_user_id', 'fk_tenant_id', name='uq_user_tenants_user_tenant')
    )
    op.create_index(op.f('ix_user_tenants_fk_tenant_id'), 'user_tenants', ['fk_tenant_id'], unique=False)
    op.create_index(op.f('ix_user_tenants_fk_user_id'), 'user_tenants', ['fk_user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.String(length=255), nullable=True),
    sa.Column('fk_user_tenant_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user_tenant_id'], ['user_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_fk_user_tenant_id'), 'refresh_tokens', ['fk_user_tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('user_tenant_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_user_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fk_role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fk_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['fk_user_tenant_id'], ['user_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_user_tenant_id', 'fk_role_id', name='uq_user_tenant_roles_user_tenant_role')
    )
    op.create_index(op.f('ix_user_tenant_roles_fk_role_id'), 'user_tenant_roles', ['fk_role_id'], unique=False)
    op.create_index(op.f('ix_user_tenant_roles_fk_user_tenant_id'), 'user_tenant_roles', ['fk_user_tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tenant_roles_fk_user_tenant_id'), table_name='user_tenant_roles')
    op.drop_index(op.f('ix_user_tenant_roles_fk_role_id'), table_name='user_tenant_roles')
    op.drop_table('user_tenant_roles')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_fk_user_tenant_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_user_tenants_fk_user_id'), table_name='user_tenants')
    op.drop_index(op.f('ix_user_tenants_fk_tenant_id'), table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index(op.f('ix_role_permissions_fk_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_fk_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_link_user_tenant_requests_fk_user_id'), table_name='link_user_tenant_requests')
    op.drop_index(op.f('ix_link_user_tenant_requests_fk_tenant_id'), table_name='link_user_tenant_requests')
    op.drop_table('link_user_tenant_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
