"""inserting type to invite and request to tenant

Revision ID: f3204cf1d800
Revises: 2c6d4f4a8f91
Create Date: 2026-04-11 15:54:21.474607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3204cf1d800'
down_revision: Union[str, Sequence[str], None] = '2c6d4f4a8f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_user_tenant_requests', sa.Column('type', sa.Enum('INVITE', 'REQUEST_ENTRY', name='link_user_tenant_request_type', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_user_tenant_requests', 'type')
    # ### end Alembic commands ###
