from __future__ import annotations

from typing import Any, Protocol


class LoggerPort(Protocol):
    def debug(self, msg: str, **fields: Any) -> None: ...
    def info(self, msg: str, **fields: Any) -> None: ...
    def warning(self, msg: str, **fields: Any) -> None: ...
    def error(self, msg: str, **fields: Any) -> None: ...
    def exception(self, msg: str, **fields: Any) -> None: ...
